# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZWMusicPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod ‘MJExtension’
  pod 'NAKPlaybackIndicatorView'

  # Pods for ZWMusicPlayer

  target 'ZWMusicPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZWMusicPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
